version: "3.2"
services:
  s0DataProvider:
    container_name: flip-${NODE_ENV}-s0DataProvider
    image: node:18.7.0
    working_dir: /app
    tty: true
    ports:
      - ${S0_DATA_PROVIDER_PORT}:80
      - ${S0_DATA_PROVIDER_PORT_DEBUGGER}:9229
    volumes:
      - s0DataProvider:/app
      - ./services/s0DataProvider/src:/app/services/s0DataProvider/src:ro
      - ./shared:/app/shared:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./services/s0DataProvider/package-lock.json:/app/package-lock.json
      - ./services/s0DataProvider/package.json:/app/package.json
      - ./services/s0DataProvider/.env:/app/.env:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 80
    command: bash -c "
      npm i --only=${NODE_ENV} &&
      npm run ${NODE_ENV}"
    depends_on:
      - mongo
  mongo:
    container_name: flip-${NODE_ENV}-mongo
    image: mongo:5.0.10
    tty: true
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes:
  s0DataProvider:
    name: flip-${NODE_ENV}-s0DataProvider
  mongo:
    name: flip-${NODE_ENV}-mongo
