version: "3.2"
services:
  s0DataProvider:
    container_name: flip-${NODE_ENV}-s0DataProvider
    image: node:18.7.0
    working_dir: /app
    tty: true
    ports:
      - ${S0_DATA_PROVIDER_PORT}:80
      - ${S0_DATA_PROVIDER_PORT_DEBUGGER}:9229
    volumes:
      - s0DataProvider:/app
      - ./services/s0DataProvider/src:/app/services/s0DataProvider/src:ro
      - ./shared:/app/shared:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./services/s0DataProvider/package-lock.json:/app/package-lock.json
      - ./services/s0DataProvider/package.json:/app/package.json
      - ./services/s0DataProvider/.env:/app/.env:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 80
    command: bash -c "
      npm i --only=${NODE_ENV} &&
      npm run ${NODE_ENV}"
    depends_on:
      - mongo

  s1DataAnalyzer:
    container_name: flip-${NODE_ENV}-s1DataAnalyzer
    image: node:18.7.0
    working_dir: /app
    tty: true
    ports:
      - ${S1_DATA_ANALYZER_PORT}:80
      - ${S1_DATA_ANALYZER_PORT_DEBUGGER}:9229
    volumes:
      - s1DataAnalyzer:/app
      - ./services/s1DataAnalyzer/src:/app/services/s1DataAnalyzer/src:ro
      - ./shared:/app/shared:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./services/s1DataAnalyzer/package-lock.json:/app/package-lock.json
      - ./services/s1DataAnalyzer/package.json:/app/package.json
      - ./services/s1DataAnalyzer/.env:/app/.env:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 80
    command: bash -c "
      npm i --only=${NODE_ENV} &&
      npm run ${NODE_ENV}"
    depends_on:
      - mongo

  s2MetricsProvider:
    container_name: flip-${NODE_ENV}-s2MetricsProvider
    image: node:18.7.0
    working_dir: /app
    tty: true
    ports:
      - ${S2_METRICS_PROVIDER_PORT}:80
      - ${S2_METRICS_PROVIDER_PORT_DEBUGGER}:9229
    volumes:
      - s2MetricsProvider:/app
      - ./services/s2MetricsProvider/src:/app/services/s2MetricsProvider/src:ro
      - ./shared:/app/shared:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./services/s2MetricsProvider/package-lock.json:/app/package-lock.json
      - ./services/s2MetricsProvider/package.json:/app/package.json
      - ./services/s2MetricsProvider/.env:/app/.env:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 80
    command: bash -c "
      npm i --only=${NODE_ENV} &&
      npm run ${NODE_ENV}"
    depends_on:
      - mongo

  mongo:
    container_name: flip-${NODE_ENV}-mongo
    image: mongo:5.0.10
    tty: true
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  # redis:
  #   container_name: flip-${NODE_ENV}-redis
  #   image: 'redis:7.0.4'
  #   command: redis-server
  #   ports:
  #     - 6379:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - redis:/var/lib/redis

volumes:
  s0DataProvider:
    name: flip-${NODE_ENV}-s0DataProvider
  s1DataAnalyzer:
    name: flip-${NODE_ENV}-s1DataAnalyzer
  s2MetricsProvider:
    name: flip-${NODE_ENV}-s2MetricsProvider
  mongo:
    name: flip-${NODE_ENV}-mongo
  # redis:
  #   name: flip-${NODE_ENV}-redis
